name: 'crowdsourcing_val_no_ties_5_price1'
mechanism: 'crowdsourcing'
bidder: ['1', '1', '1', '1', '1']
o_space: {'1': [0.0 ,1.0]}
a_space: {'1': [0.0, 1.0]}
param_prior: {'distribution':'uniform'}
param_util: {
  'tiebreaking':'lose', 
  'type':'valuation',
  'price': [1., 0.],
  }
n: 128
m: 128
bne_known: True