name: 'difference_form_cost_0.1'
bidder: ['1', '1']
o_space: {'1': [0.1 ,1.1]}
a_space: {'1': [0.0, 2.2]}
param_prior: {'distribution':'uniform'}
csf: 'difference_form_cost'
param_csf: 0.1
n: 128
m: 128