name: 'tullock_lottery_weak_vs_weak'
bidder: ['weak', 'weak']
o_space: {'weak': [0.0 ,1.0]}
a_space: {'weak': [0.0, 0.5]}
param_prior: {'distribution':'uniform'}
csf: 'ratio_form_valuation'
param_csf: 1
n: 128
m: 128
bne_known: False