bidder: ['weak', 'strong']
o_space: {'weak': [0.0 ,1.0], 'strong': [1.0, 2.0]}
a_space: {'weak': [0.0, 0.3], 'strong': [0.0, 0.4]}
param_prior: {'distribution':'uniform'}
param_util : {
  'type': 'valuation',
  'csf': 'ratio_form',
  'csf_parameter': 1,
}
n: 64
m: 64