name: 'split_award'
bidder: ['1', '1']
o_space: {'1': [1.0 ,1.4]}
a_space: {'1': [[0.4 ,2.5], [0.4 ,2.5]]}
param_prior: {'distribution':'uniform'}
param_util: { 'tie_breaking': 'lose', 'scale': 0.3}
n: 64
m: 64
bne_known: True